"use client";

import * as React from "react";
import { ShieldAlert, WifiOff, Zap } from "lucide-react";
import { toast } from "sonner";

import { LabelChip } from "@/components/savera/LabelChip";
import { Button } from "@/components/ui/button";

import { DeviceFrame, EyebrowPill, LandingSection, Reveal } from "./primitives";

/* ------------------------------------------------------------------ */
/* Lifeline — official alerts + Automated Demand Response, shown as a  */
/* phone mock-up. Everything here is simulated demo content: alerts   */
/* are human-published by a department and never generated by AI.     */
/* ------------------------------------------------------------------ */

const BULLETS: ReadonlyArray<string> = [
  "Planned interruptions for a ward, published with a window and a reason",
  "ADR events: approve, auto-apply or decline a 30-minute AC set-point change",
  "Every alert is labelled Official and never generated by AI",
];

type DrChoice = "Approve" | "Auto" | "Decline";

export function LifelineSection() {
  const respond = React.useCallback((choice: DrChoice) => {
    toast("Simulated — sign in to respond", {
      description: `${choice} · Demand response 18:30–19:00 (demo preview)`,
    });
  }, []);

  return (
    <LandingSection id="lifeline" tone="page" aria-labelledby="lifeline-title">
      <div className="grid gap-12 lg:grid-cols-2 lg:items-center lg:gap-16">
        {/* Phone mock-up — first on mobile, right column on desktop */}
        <Reveal className="relative order-first lg:order-last" delay={0.08} y={24}>
          <div
            aria-hidden
            className="pointer-events-none absolute top-1/2 left-1/2 h-[360px] w-[360px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-tone-critical/10 blur-[110px]"
          />
          <div
            aria-hidden
            className="pointer-events-none absolute right-[10%] bottom-0 h-[220px] w-[260px] rounded-full bg-positive/10 blur-[100px]"
          />

          <DeviceFrame time="7:42" role="group" aria-label="Preview of SAVERA notifications on a phone (simulated)">
            <div className="flex min-h-[400px] flex-col gap-3">
              {/* Official alert */}
              <article className="rounded-2xl border border-tone-critical/30 bg-tone-critical/10 p-3">
                <div className="flex items-center justify-between gap-2">
                  <div className="flex min-w-0 items-center gap-1.5">
                    <ShieldAlert className="size-3.5 shrink-0 text-tone-critical" aria-hidden />
                    <span className="truncate font-mono text-2xs font-semibold tracking-wider text-tone-critical uppercase">
                      Savera · Electricity Department
                    </span>
                  </div>
                  <span className="shrink-0 font-mono text-2xs text-faint">now</span>
                </div>
                <p className="mt-2 text-xs leading-relaxed text-foreground">
                  <span className="font-bold">Official alert</span> — Planned interruption, Ward 24: 11:00–13:30
                  today for feeder maintenance. Possible low voltage 10:45–11:00.
                </p>
                <div className="mt-2.5">
                  <LabelChip kind="official" size="sm" />
                </div>
              </article>

              {/* Demand response */}
              <article className="rounded-2xl border border-positive/30 bg-positive/10 p-3">
                <div className="flex items-center justify-between gap-2">
                  <div className="flex min-w-0 items-center gap-1.5">
                    <Zap className="size-3.5 shrink-0 text-positive" aria-hidden />
                    <span className="truncate font-mono text-2xs font-semibold tracking-wider text-positive uppercase">
                      Demand response · 18:30–19:00
                    </span>
                  </div>
                </div>
                <p className="mt-2 text-xs leading-relaxed text-foreground">Raise AC to 26 °C for 30 minutes?</p>
                <div className="mt-2.5 flex flex-wrap items-center gap-1.5">
                  <Button
                    type="button"
                    size="sm"
                    variant="positive"
                    className="h-7 px-2.5 text-2xs"
                    onClick={() => respond("Approve")}
                  >
                    Approve
                  </Button>
                  <Button
                    type="button"
                    size="sm"
                    variant="outline"
                    className="h-7 px-2.5 text-2xs"
                    onClick={() => respond("Auto")}
                  >
                    Auto
                  </Button>
                  <Button
                    type="button"
                    size="sm"
                    variant="ghost"
                    className="h-7 px-2.5 text-2xs"
                    onClick={() => respond("Decline")}
                  >
                    Decline
                  </Button>
                </div>
              </article>

              {/* Low connectivity glyph */}
              <div className="flex flex-1 flex-col items-center justify-center gap-2 py-4 text-center">
                <WifiOff className="size-8 text-faint" aria-hidden />
                <p className="font-mono text-2xs tracking-wider text-faint uppercase">
                  Low connectivity mode — last sync 7:41
                </p>
              </div>

              {/* Offline cache pill */}
              <div className="mx-auto w-fit rounded-full border border-border bg-muted px-3 py-1 font-mono text-2xs font-semibold tracking-wider text-soft uppercase">
                Offline cache · 3 alerts kept
              </div>
            </div>
          </DeviceFrame>
        </Reveal>

        {/* Copy */}
        <div className="order-last flex flex-col gap-6 lg:order-first">
          <Reveal>
            <EyebrowPill tone="critical" icon={ShieldAlert}>
              Official alerts · Demand response
            </EyebrowPill>
          </Reveal>

          <Reveal delay={0.08}>
            <h2
              id="lifeline-title"
              className="text-3xl font-extrabold tracking-tight text-foreground sm:text-4xl lg:text-5xl"
            >
              Lifeline when the
              <br />
              <span className="text-tone-critical">grid is stressed.</span>
            </h2>
          </Reveal>

          <Reveal delay={0.16}>
            <p className="max-w-xl text-sm leading-relaxed text-soft sm:text-base">
              When the city grid or a water feeder is under stress, the department publishes an official, human-signed
              alert and an Automated Demand Response event. Citizens see it in their notifications, on the dashboard
              banner and — with a compatible connection — as a broadcast{" "}
              <LabelChip kind="integration-ready" size="sm" className="align-middle" />.
            </p>
          </Reveal>

          <Reveal delay={0.24}>
            <ul className="flex flex-col gap-3">
              {BULLETS.map((text) => (
                <li key={text} className="flex items-start gap-3 text-sm text-foreground">
                  <span className="mt-2 size-1.5 shrink-0 rounded-full bg-tone-critical" aria-hidden />
                  <span>{text}</span>
                </li>
              ))}
            </ul>
          </Reveal>

          <Reveal delay={0.32}>
            <p className="font-mono text-2xs tracking-wider text-faint uppercase">
              Demo · Ward 24 · Electricity Department (Raichur) · Water Supply Board
            </p>
          </Reveal>
        </div>
      </div>
    </LandingSection>
  );
}
