"use client";

import * as React from "react";
import Link from "next/link";
import { CalendarClock, ChevronRight } from "lucide-react";

import { formatDate, formatDateTime } from "@/lib/format";
import { parseIso } from "@/lib/dates";
import { cn } from "@/lib/utils";
import { DEPARTMENT_LABEL, type Tone } from "@/types/common";
import {
  OFFICIAL_ALERT_TYPE_LABEL,
  type OfficialAlert,
  type OfficialAlertStatus,
} from "@/types/connected";

import { LabelChip } from "./LabelChip";
import { StatusBadge } from "./StatusBadge";
import { STREAM_CLASSES } from "./tone";
import { StreamIcon } from "./StreamIcon";

export const ALERT_STATUS_TONE: Record<OfficialAlertStatus, Tone> = {
  scheduled: "moderate",
  active: "critical",
  resolved: "normal",
};

export const ALERT_STATUS_LABEL: Record<OfficialAlertStatus, string> = {
  scheduled: "Scheduled",
  active: "Active",
  resolved: "Resolved",
};

function timeOnly(iso: string): string {
  const d = parseIso(iso);
  if (Number.isNaN(d.getTime())) return "—";
  const hours = d.getHours();
  const h12 = hours % 12 === 0 ? 12 : hours % 12;
  const meridiem = hours >= 12 ? "PM" : "AM";
  return `${h12}:${String(d.getMinutes()).padStart(2, "0")} ${meridiem}`;
}

/** `22 Sep 2026, 7:00 AM – 9:00 AM` (same day) or two full timestamps. */
export function formatAlertWindow(start: string, end: string): string {
  const sameDay = start.slice(0, 10) === end.slice(0, 10);
  if (sameDay) return `${formatDate(start)}, ${timeOnly(start)} – ${timeOnly(end)}`;
  return `${formatDateTime(start)} – ${formatDateTime(end)}`;
}

export interface AlertBannerProps extends Omit<React.ComponentProps<"div">, "onClick"> {
  alert: OfficialAlert;
  /** Single-line variant for lists and drawers. */
  compact?: boolean;
  /** Link target for the whole banner (e.g. `/citizen/alerts/alert-001`). */
  href?: string;
  onClick?: (alert: OfficialAlert) => void;
  /** Hide the "Published by" line. */
  hidePublisher?: boolean;
}

/**
 * Official disruption alert banner (MASTER_PROMPT §2.8): published by a
 * department account, never generated by AI. Shows the `Official` chip, the
 * stream icon, title, window, reason and status.
 */
export function AlertBanner({
  alert,
  compact = false,
  href,
  onClick,
  hidePublisher = false,
  className,
  ...props
}: AlertBannerProps) {
  const tone = ALERT_STATUS_TONE[alert.status];
  const s = STREAM_CLASSES[alert.stream];
  const interactive = Boolean(href || onClick);

  const body = compact ? (
    <div className="flex min-w-0 flex-1 items-center gap-3">
      <StreamIcon stream={alert.stream} variant="tile" size="sm" labelled />
      <div className="min-w-0 flex-1">
        <div className="flex flex-wrap items-center gap-x-2 gap-y-1">
          <LabelChip kind="official" size="sm" />
          <p className="text-foreground truncate text-sm font-semibold">{alert.title}</p>
        </div>
        <p className="text-muted-foreground mt-0.5 flex items-center gap-1.5 text-xs">
          <CalendarClock aria-hidden="true" className="size-3 shrink-0" />
          <span className="truncate">{formatAlertWindow(alert.windowStart, alert.windowEnd)}</span>
        </p>
      </div>
      <StatusBadge
        tone={tone}
        label={ALERT_STATUS_LABEL[alert.status]}
        size="sm"
        pulse={alert.status === "active"}
      />
      {interactive ? (
        <ChevronRight aria-hidden="true" className="text-muted-foreground size-4 shrink-0" />
      ) : null}
    </div>
  ) : (
    <div className="flex min-w-0 flex-1 flex-col gap-3 sm:flex-row sm:items-start sm:gap-4">
      <StreamIcon stream={alert.stream} variant="tile" size="lg" labelled />
      <div className="min-w-0 flex-1">
        <div className="flex flex-wrap items-center gap-2">
          <LabelChip kind="official" size="sm" />
          <span className="text-muted-foreground text-xs font-semibold tracking-wide uppercase">
            {OFFICIAL_ALERT_TYPE_LABEL[alert.type]}
          </span>
        </div>
        <h3 className="font-display text-foreground mt-1.5 text-base leading-tight font-bold tracking-tight sm:text-lg">
          {alert.title}
        </h3>
        <p className="text-foreground/80 mt-1.5 flex items-start gap-1.5 text-sm">
          <CalendarClock aria-hidden="true" className="mt-0.5 size-4 shrink-0" />
          <span>
            <span className="text-muted-foreground">Window: </span>
            {formatAlertWindow(alert.windowStart, alert.windowEnd)}
          </span>
        </p>
        <p className="text-muted-foreground mt-1.5 text-sm leading-relaxed">
          <span className="text-foreground/70 font-semibold">Reason: </span>
          {alert.reason}
        </p>
        {!hidePublisher ? (
          <p className="text-muted-foreground mt-2 text-xs">
            Published by {DEPARTMENT_LABEL[alert.publishedBy]} · {formatDateTime(alert.publishedAt)}
          </p>
        ) : null}
      </div>
      <div className="flex shrink-0 items-center gap-2 sm:flex-col sm:items-end">
        <StatusBadge
          tone={tone}
          label={ALERT_STATUS_LABEL[alert.status]}
          pulse={alert.status === "active"}
        />
        {interactive ? (
          <span className="text-muted-foreground inline-flex items-center gap-1 text-xs font-semibold">
            Details
            <ChevronRight aria-hidden="true" className="size-3.5" />
          </span>
        ) : null}
      </div>
    </div>
  );

  const surface = cn(
    "glass flex w-full items-center rounded-2xl border-l-4 text-left transition-colors",
    s.border,
    compact ? "px-4 py-3" : "p-5",
    alert.status === "active" && "border-l-red-500",
    alert.status === "scheduled" && "border-l-amber-500",
    alert.status === "resolved" && "border-l-positive",
    interactive &&
      "hover:border-foreground/20 focus-visible:ring-ring/60 cursor-pointer outline-none focus-visible:ring-2",
    className,
  );

  if (href) {
    return (
      <div
        data-slot="alert-banner"
        role="region"
        aria-label={`Official alert: ${alert.title}`}
        {...props}
      >
        <Link href={href} onClick={() => onClick?.(alert)} className={surface}>
          {body}
        </Link>
      </div>
    );
  }

  if (onClick) {
    return (
      <div
        data-slot="alert-banner"
        role="region"
        aria-label={`Official alert: ${alert.title}`}
        {...props}
      >
        <button type="button" onClick={() => onClick(alert)} className={surface}>
          {body}
        </button>
      </div>
    );
  }

  return (
    <div
      data-slot="alert-banner"
      role="region"
      aria-label={`Official alert: ${alert.title}`}
      className={surface}
      {...props}
    >
      {body}
    </div>
  );
}
