import type { Department, IsoDate, IsoDateTime, Stream } from "./common";
import type { ElectricityBill } from "./electricity";
import type { Appliance, Household } from "./household";
import type { LpgCylinder } from "./lpg";

export type OfficialAlertType = "power_interruption" | "water_disruption" | "lpg_advisory";
export type OfficialAlertStatus = "scheduled" | "active" | "resolved";

/** Official disruption alert — published by a department account, never generated by AI. */
export interface OfficialAlert {
  id: string;
  stream: Stream;
  type: OfficialAlertType;
  title: string;
  areaIds: string[];
  wardIds: string[];
  windowStart: IsoDateTime;
  windowEnd: IsoDateTime;
  reason: string;
  status: OfficialAlertStatus;
  publishedBy: Department;
  publishedByUserId: string;
  publishedAt: IsoDateTime;
  updates: { at: IsoDateTime; text: string; status: OfficialAlertStatus }[];
}

export type OfficialAlertInput = Omit<
  OfficialAlert,
  "id" | "publishedAt" | "updates" | "status"
> & {
  status?: OfficialAlertStatus;
};

export type ConsentSource =
  "electricity_board" | "water_board" | "lpg_provider" | "municipal_records";

/** Consent granted for a simulated "API Setu-style" import (MASTER_PROMPT §9.4). */
export interface ConsentGrant {
  source: ConsentSource;
  householdId: string;
  /** Exactly which fields were shared. */
  fields: string[];
  grantedAt: IsoDateTime;
  status: "active" | "revoked";
  revokedAt?: IsoDateTime;
}

/** Data returned by `simulateImport`; every record carries `source: 'import'`. */
export interface ImportedFields {
  household?: Partial<Household>;
  bills?: ElectricityBill[];
  appliances?: Appliance[];
  cylinders?: LpgCylinder[];
  water?: Household["water"];
}

/** A utility bill awaiting (simulated) payment in the Services Hub. */
export interface BillDue {
  id: string;
  householdId: string;
  stream: "electricity" | "water";
  amount: number;
  dueDate: IsoDate;
  /** Billing period label, e.g. "Sep 2026". */
  period: string;
  status: "due" | "paid";
  /** Transaction ref once paid. */
  paidRef?: string;
}

export type ServiceTransactionKind = "payment" | "booking" | "reminder";

/** Simulated payment / booking / reminder transaction. */
export interface ServiceTransaction {
  ref: string;
  kind: ServiceTransactionKind;
  householdId: string;
  amount?: number;
  description: string;
  status: "success" | "pending" | "failed";
  createdAt: IsoDateTime;
  simulated: true;
  receipt?: { id: string; method: string; at: IsoDateTime };
}

export type ReminderKind = "lpg_refill" | "bill" | "custom";

export interface Reminder {
  id: string;
  householdId: string;
  title: string;
  body: string;
  dueAt: IsoDateTime;
  kind: ReminderKind;
  createdAt: IsoDateTime;
}

export type TwinDeviceId = "ac" | "fan" | "lights" | "fridge" | "geyser" | "tv";
export type TwinRoomId = "living_room" | "bedroom" | "kitchen" | "bathroom" | "utility";

/** A device in the "My Home" digital twin (Simulation — Digital Twin Prototype). */
export interface TwinDevice {
  id: TwinDeviceId;
  label: string;
  on: boolean;
  /** Current simulated draw. */
  kw: number;
  /** Draw at full load. */
  ratedKw: number;
  setpointC?: number;
  hoursPerDay: number;
  /** Eligible for demand response (AC, geyser) vs protected (fridge). */
  flexible: boolean;
  /** lucide-react icon name. */
  icon: string;
  room?: TwinRoomId;
}

export const OFFICIAL_ALERT_TYPE_LABEL: Record<OfficialAlertType, string> = {
  power_interruption: "Planned power interruption",
  water_disruption: "Water supply disruption",
  lpg_advisory: "LPG distribution advisory",
};

export const CONSENT_SOURCE_LABEL: Record<ConsentSource, string> = {
  electricity_board: "Electricity Board",
  water_board: "Water Board",
  lpg_provider: "LPG Provider",
  municipal_records: "Municipal Records",
};
