import type { Department, IsoDateTime, Role, Stream } from "./common";

export type NotificationType =
  | "water_case"
  | "water_action"
  | "lpg"
  | "electricity"
  | "dr_event"
  | "official_alert"
  | "broadcast"
  | "green_score"
  | "system"
  | "reminder"
  | "service";

/**
 * Who sees a notification: `role` must match and, when a narrower field is set,
 * the user's household / area / ward / department / id must be included.
 */
export interface NotificationTarget {
  role: Role;
  householdIds?: string[];
  areaIds?: string[];
  wardIds?: string[];
  departments?: Department[];
  userIds?: string[];
}

export interface Notification {
  id: string;
  target: NotificationTarget;
  type: NotificationType;
  stream?: Stream;
  title: string;
  body: string;
  /** Deep link opened on click. */
  href?: string;
  createdAt: IsoDateTime;
  /** User ids that have read it. */
  readBy: string[];
  /** Published by a department account (never AI-generated). */
  official?: boolean;
  /** Generated by a simulated integration. */
  simulated?: boolean;
}

export type NotificationInput = Omit<Notification, "id" | "createdAt" | "readBy">;
